language: node_js
cache:
  directories:
  - node_modules
node_js:
- 12.16.1
notifications:
  email: false
script:
- npm run build
before_deploy:
- cd build
deploy:
  skip_cleanup: true
  provider: s3
  bucket: com.shepherdjerred.tripsim
  access_key_id: AKIAJIZ6FW2EW52PBBZA
  secret_access_key:
    secure: Em0jvABlQphSsyUqx2G6zkt+/x/NxqSXTmb0FI+Ng3Q0QlXpa2EAZ7eN8o1cgwuWxz2tQRwLI1J6E6XXiozeoi4Sso1N1XjrdV2Lg40VFAB1oZZdLgERl1Lju6tukRxZJLQNCto1TLnIbHxvPqWRMRWhSsAvVWfajoD9PQ/AT+ANum0WQn/FEXDzDyv65pco93ZdbV+r3WfgmfVL1u7L0kWex7d6IK6hyYJ5QR4xc3PSZmJiWhu6fws0lS96a7xqaisiHWaBg3QJJh8EOH0aJdSMa0uR0STnbnWNYdMafZ8FHfSjhhR/3I9jRuP0ZozemkwgITV/Ij5ScbIzTLm2eGiSGtXaEa5sbbEgx8dbFev4y2TXAJbVxKB4Z/UISeo2iju/XhkBf6W5LNe5fvPPgQ8yjQ0nPePW17djIplrcR4ljC0BnT+XJTJKnmRk+x53Hs7bEwaC+Ndt/KA9Zf8P8rJTBzSOUMNPB5fagaSk42GQKegh+0hL7zxqvH/yT7V3M8ZfjoKg4kajjR0pzg4KbcEWhXT8GGWYIP1bxMVbgLXohwcrR2zacQj1Rdwq8lNzOdK/1fLuYBQlqNpQ+WAM+T7KZt9LYgjRmBZvkKbfD4J5bFOPoSyrXHKPlKHTd0k53wE8NgcQvMa9fqrLTVgT6NoNNTUI7K1l+phDJQLQbvI=
